### ISSUE TITLE
Flip the visualization of the dense input to better match the positions of the wire.

### ISSUE THREAD

**Issue by daviscook477** [Hexicube/ONI-DenseLogic#14]
Only maybe. See what klei does with the ribbon reader/writer first.

**Comment by Hexicube** [comment]
The ribbon input visualisation doesn't rotate but the wires do, "fixing" it for the default rotation would simply break it for a 180 degree rotation.

**Comment by daviscook477** [comment]
So does it work flipping it work sense we are only using it with R90 rotation.
