### ISSUE TITLE
Dense Logic Gate (and probably others) show on top of cables in automation view

### ISSUE THREAD

**Issue by Hexicube** [Hexicube/ONI-DenseLogic#39]
Vanilla gates show under cables, whilst readers/writers show on top. Should probably do it case-by-case.

**Comment by peterhaneve** [comment]
Are you sure that this is by design, or just an artifact of load order which is usually unspecified?

**Comment by Hexicube** [comment]
I'm almost positive it's intentional, it'll be the layer gates are on.
